[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
urls = { Repository = "https://github.com/Starry-OvO/aiotieba-reviewer/" }
name = "aiotieba-reviewer"
description = "Reviewer Framework based on Aiotieba"
readme = "README.md"
requires-python = ">=3.8"
authors = [{ name = "Starry-OvO", email = "starry.qvq@gmail.com" }]
keywords = ["tieba"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Framework :: AsyncIO",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: The Unlicense (Unlicense)",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Topic :: Internet :: WWW/HTTP :: Session",
]
dependencies = ["aiotieba[img,speedup]<4.0,>=2.10.3", "aiomysql<0.2,>=0.1.0"]
dynamic = ["version"]

[tool.setuptools.packages.find]
include = ["aiotieba_reviewer*"]

[tool.setuptools.dynamic]
version = { attr = "aiotieba_reviewer.__version__.__version__" }

[tool.black]
line-length = 120
skip-string-normalization = true
extend-exclude = ["*_pb2.py"]
target-version = ["py38"]

[tool.isort]
profile = "black"
line_length = 120
py_version = "38"
extend_skip_glob = ["*_pb2.py"]

[tool.ruff]
line-length = 120
select = ["W", "E", "F", "I"]
ignore = ["E402", "E501"]
target-version = "py38"
extend-exclude = ["*_pb2.py"]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-q"
testpaths = ["tests"]
required_plugins = "pytest-asyncio"
asyncio_mode = "strict"
